targets:
  $default:
    builders:
      # A SharedPartBuilder which uses the combining builder
      source_gen:combining_builder:
        options:
          build_extensions:
            '^lib/resources/realm/model/{{}}.dart': 'lib/resources/realm/model/generated/{{}}.g.dart'